### ISSUE TITLE
[SPIKE] Investigate Ironcore-Alloy Kotlin vs. TSC-Java performance difference

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/ironcore-alloy#113]
For large documents, IA Kotlin is faster than TSC-Java, but for small documents (under 2Kb), it is slower. Initial investigation suggests it might be an issue with the connection to the TSP to make the wrap call. Check whether there is anything that can speed up the IA rust - TSP calls that would improve the Kotlin performance.

**Comment by giarc3** [comment]
Initial testing didn't yield any meaningful improvements. It seems like ~40us is likely the FFI cost we have to pay, and that's significant for small document operations.
