### ISSUE TITLE
Add support for prior document types to Standard

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/ironcore-alloy#21]
For the first release of Alloy we cut just what we needed to support the new style with doc v4 and prefixed ids. For it to fully replace the TSC it needs to support our document styles pre-v4. Add support for decrypting older documents and add it to the flow for all paths that exist at the time of this ticket being worked.

**Comment by coltfred** [comment]
This is only for saas shield, since standalone didn't exist in v3. I think this should just be rekey and decrypt since batch decrypt doesn't exist, yet.

**Comment by giarc3** [comment]
For the detached case (which this ticket is for), we decided to not support the case where there is no key id header because those do not exist today. We will still have to support it for the attached case in the future.
