### ISSUE TITLE
Add support for standard attached document ops

### ISSUE THREAD

**Issue by BobWall23** [IronCoreLabs/ironcore-alloy#22]
The design includes attached document ops in addition to detached. Attached is in use in cloaked search, and it'd be great to replace the adhoc TSC there with Alloy, in addition to the functionality possibly being useful to others.

**Comment by coltfred** [comment]
For this I'm planning on implementing:

```rust
      trait StandardAttachedDocumentOps {
        async fn encrypt(plaintext_field: PlaintextBytes, metadata: &IronCoreMetadata) -> EncryptedBytes;
        async fn decrypt(attached_field: EncryptedBytes, metadata: &IronCoreMetadata) -> PlaintextBytes;
        async fn get_searchable_prefix(id: u32) -> Vec<u8>
      }
```
this will allow basic usage of attached documents. When closing this I will write tickets for any of the remaining functions that will be needed for attached ops.
