### ISSUE TITLE
Support NodeJS

### ISSUE THREAD

**Issue by mdgozza-alt** [IronCoreLabs/ironcore-alloy#40]
It would be very helpful for us if we could generate bindings for this SDK for NodeJS

**Comment by skeet70** [comment]
We do eventually plan to support Node. If Node support is added to [uniffi](https://github.com/mozilla/uniffi-rs), we'll quickly follow on adding bindings to this library (PRs are welcome there).

Could you elaborate on your Node usecase, and how you found this library? If it fits within the "standard" portion of the SDK, our [TSC-nodejs](https://github.com/IronCoreLabs/tenant-security-client-nodejs) may provide enough functionality for you.

**Comment by skeet70** [comment]
I'm going to close this in favor of #18 that we already have tracking it. Feel free to leave more information here though if you'd like.
